// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	helloApi "github.com/wego2023/wesso/api/kitex_gen/hello"
	"github.com/wego2023/wesso/api/kitex_gen/hello/hello"
	"log"
	"time"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	// 创建client
	helloClient, err := hello.NewClient("hello", client.WithHostPorts("0.0.0.0:8888"))
	if err != nil {
		log.Fatal(err)
	}
	req := &helloApi.Request{Message: "Hello World"}
	resp, err := helloClient.Hello(context.Background(), req, callopt.WithRPCTimeout(3*time.Second))
	if err != nil {
		log.Fatal(err)
	}
	log.Println(resp)
	log.Println(resp.Message)
	c.JSON(consts.StatusOK, utils.H{
		"message": resp.Message,
	})
}
