// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/config"
)

func main() {

	h := server.Default(config.Option{
		F: func(o *config.Options) {
			o.Addr = ":8001"
		},
	})

	register(h)
	h.Spin()
}
