// Code generated by Kitex v0.5.1. DO NOT EDIT.

package hello

import (
	server "github.com/cloudwego/kitex/server"
	hello "github.com/wegoteam/wesso/api/kitex_gen/hello"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler hello.Hello, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
