// Code generated by Kitex v0.5.1. DO NOT EDIT.
package hello

import (
	server "github.com/cloudwego/kitex/server"
	hello "github.com/wego2023/wesso/api/kitex_gen/hello"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler hello.Hello, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
